#! /usr/local/bin/node

var spawn = require('child_process').spawn;
var gotoGreen = require('./src/getGreen');

if (process.argv.length !== 3) {
	console.log('ERROR! One argument is required');
	console.log('usage: newBranch <newBranchName>');
	process.exit(1);
}

var newBranchName = process.argv[2];

gotoGreen(function (commits) {
	var spawnedProcess = spawn(__dirname + '/bin/branch-repos.sh', [newBranchName, commits.appsdk.commit, commits.appCatalog.commit, commits.alm.commit]);

	spawnedProcess.stdout.on('data', function (data) {
		process.stdout.write(data);
	});

	spawnedProcess.stderr.on('data', function (data) {
		process.stdout.write('stderr: ' + data);
	});

	spawnedProcess.on('close', function (code) {
		process.stdout.write('child process exited with code ' + code);
	});
});